spring.datasource.url=jdbc:mysql://mysql-f28934f-auto-mart-grading-project.d.aivencloud.com:18643/defaultdb?ssl-mode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_mjjXWzqNsjkzM9Xz5PC

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=${PORT:8080}